/*
 * File: app/store/ScenarioBizModelsStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.store.ScenarioBizModelsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'DecisionLink.model.ScenarioBizModels',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'DecisionLink.model.ScenarioBizModels',
        storeId: 'ScenarioBizModelsStore',
        proxy: {
            type: 'jsonp',
            reader: {
                type: 'json',
                rootProperty: 'business_models'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        length = store.data.items.length;
        if (length === 0) {
            Ext.ComponentQuery.query('opportunitycarousel #opportunitySituationPanel #bizModelsList')[0].setHidden(true);
            Ext.ComponentQuery.query('opportunitycarousel #opportunitySituationPanel #bizModelsTitle')[0].setHidden(true);
        } else {
            records = [];
            for(i = 0; i < length; i++) {
                if (store.data.items[i].data.selected) {
                    records[records.length] = store.data.items[i];
                }
            }
            Ext.ComponentQuery.query('opportunitycarousel #opportunitySituationPanel #bizModelsList')[0].select(records);

            Ext.ComponentQuery.query('opportunitycarousel #opportunitySituationPanel #bizModelsList')[0].setHidden(false);
            Ext.ComponentQuery.query('opportunitycarousel #opportunitySituationPanel #bizModelsTitle')[0].setHidden(false);
        }
    }

});