/*
 * File: app/store/ValidateStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.store.ValidateStore', {
    extend: 'Ext.data.Store',

    requires: [
        'DecisionLink.model.Validate',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'DecisionLink.model.Validate',
        storeId: 'ValidateStore',
        proxy: {
            type: 'jsonp',
            reader: {
                type: 'json',
                rootProperty: 'results'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        var success,
            id,
            account_id,
            user_name,
            account_name;

        success = store.data.items[0].data.success;
        id = store.data.items[0].data.id;
        account_id = store.data.items[0].data.account_id;
        user_name = store.data.items[0].data.user_name;
        account_name = store.data.items[0].data.account_name;
        email = store.data.items[0].data.email;


        DecisionLink.app.setUserId(id);
        DecisionLink.app.setValidated(success);
        DecisionLink.app.setAccountId(account_id);
        DecisionLink.app.setUserName(user_name);
        DecisionLink.app.setAccountName(account_name);
        DecisionLink.app.setEmail(email);

        if (!success) {
            alert("Login unsuccessful");
        }
    }

});