/*
 * File: app/store/VersionStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.store.VersionStore', {
    extend: 'Ext.data.Store',

    requires: [
        'DecisionLink.model.Version',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'DecisionLink.model.Version',
        storeId: 'VersionStore',
        proxy: {
            type: 'jsonp',
            reader: {
                type: 'json'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        version = store.data.items[0].data.version;

        Ext.ComponentQuery.query('accountpanel #currVersionLabel')[0].setHtml(version);
    }

});