/*
 * File: app/view/AccountPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.view.AccountPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.accountpanel',

    requires: [
        'Ext.Spacer',
        'Ext.field.Email',
        'Ext.Button',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'textfield',
                itemId: 'accountNameField',
                label: 'Account',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'textfield',
                itemId: 'usernameField',
                label: 'Username',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'emailfield',
                itemId: 'emailField',
                label: 'Email',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'spacer',
                height: 15
            },
            {
                xtype: 'button',
                itemId: 'changePasswordButton',
                margin: 10,
                text: 'Change Password'
            },
            {
                xtype: 'spacer',
                height: 15
            },
            {
                xtype: 'button',
                itemId: 'changeCurrencyButton',
                margin: 10,
                text: 'Change Currency Preference'
            },
            {
                xtype: 'spacer',
                height: 15
            },
            {
                xtype: 'button',
                hidden: true,
                itemId: 'logoutButton',
                margin: 10,
                text: 'Logout'
            },
            {
                xtype: 'label',
                html: '<p>App Version 0.0.4 Build 0.0.5</p>',
                itemId: 'appVersionLabel',
                margin: 3
            },
            {
                xtype: 'label',
                itemId: 'currVersionLabel',
                margin: 3
            },
            {
                xtype: 'list',
                hidden: true,
                itemId: 'versionHiddenList',
                margin: 3,
                itemTpl: [
                    '<div>List Item {string}</div>'
                ]
            }
        ]
    }

});