/*
 * File: app/view/ChangePasswordPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ChangePasswordPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.changepasswordpanel',

    requires: [
        'Ext.field.Text',
        'Ext.Spacer',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'textfield',
                itemId: 'currentPasswordField',
                label: 'Current Password',
                labelWidth: '40%',
                labelWrap: true
            },
            {
                xtype: 'spacer',
                height: 15
            },
            {
                xtype: 'textfield',
                itemId: 'newPasswordField',
                label: 'New Password',
                labelWidth: '40%',
                labelWrap: true
            },
            {
                xtype: 'spacer',
                height: 15
            },
            {
                xtype: 'textfield',
                itemId: 'confirmPasswordField',
                label: 'Confirm Password',
                labelWidth: '40%',
                labelWrap: true
            },
            {
                xtype: 'spacer',
                height: 15
            },
            {
                xtype: 'button',
                itemId: 'changePasswordButton',
                margin: 5,
                text: 'Change Password'
            }
        ]
    }

});