/*
 * File: app/view/CompetitiveCarousel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CompetitiveCarousel', {
    extend: 'Ext.carousel.Carousel',
    alias: 'widget.competitivecarousel',

    requires: [
        'Ext.Panel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'panel',
                itemId: 'kpiListPanel',
                layout: 'fit',
                items: [
                    {
                        xtype: 'list',
                        itemId: 'kpisList',
                        itemTpl: [
                            '<div class=“info” width=“40” height=“40”/>{name}<br/><small>KPI Total: ${sqq_value}</small>'
                        ],
                        store: 'KpisStore'
                    }
                ]
            },
            {
                xtype: 'panel',
                itemId: 'peerPerformancePanel',
                layout: 'fit',
                items: [
                    {
                        xtype: 'list',
                        itemId: 'peerPerformanceList',
                        itemTpl: [
                            '<tpl if="opportunity &gt; 0">',
                            '    <div class=“info” width=“40” height=“40” style="color:green"/>{name}',
                            '<tpl else>',
                            '    <div class=“info” width=“40” height=“40”/>{name}',
                            '</tpl>'
                        ],
                        store: 'CompRatiosStore'
                    }
                ]
            },
            {
                xtype: 'panel',
                itemId: 'closestPeersPanel',
                layout: 'fit',
                items: [
                    {
                        xtype: 'list',
                        itemId: 'closestPeersList',
                        itemTpl: [
                            '<div class=“info” width=“40” height=“40”/>{name}<br/><small>${revenue}</small>'
                        ],
                        store: 'ClosestPeersStore'
                    }
                ]
            }
        ]
    }

});