/*
 * File: app/view/DNBCarousel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DNBCarousel', {
    extend: 'Ext.carousel.Carousel',
    alias: 'widget.dnbcarousel',

    requires: [
        'Ext.Panel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'panel',
                itemId: 'overviewPanel',
                layout: 'fit',
                items: [
                    {
                        xtype: 'list',
                        itemId: 'dnbOverviewList',
                        itemTpl: [
                            '<ul>',
                            '    <li>Name: {name}</li>',
                            '    <br/>',
                            '    <li>Qualitative Overview (Real-Time from DnB):</li>',
                            '    <br/>',
                            '    <li>{synopsis}</li>',
                            '</ul>'
                        ],
                        store: 'DNBOverviewStore'
                    }
                ]
            },
            {
                xtype: 'panel',
                itemId: 'divisionsPanel',
                layout: 'fit',
                items: [
                    {
                        xtype: 'list',
                        itemId: 'divisionsList',
                        itemTpl: [
                            '<div class=“info” width=“40” height=“40”/>Company: {name}<br/><small>{city}, {state}, {country}</small>'
                        ],
                        store: 'DivisionsStore'
                    }
                ]
            },
            {
                xtype: 'panel',
                itemId: 'competitorsPanel',
                layout: 'fit',
                items: [
                    {
                        xtype: 'list',
                        itemId: 'competitorsList',
                        itemTpl: [
                            '<div class=“info” width=“40” height=“40”/>Company: {name}<br/><small>{city}, {state}, {country}</small>'
                        ],
                        store: 'CompetitorsStore'
                    }
                ]
            },
            {
                xtype: 'panel',
                itemId: 'employeesPanel',
                layout: 'fit',
                items: [
                    {
                        xtype: 'list',
                        itemId: 'employeesList',
                        itemTpl: [
                            '<div class=“info” width=“40” height=“40”/>{fullName}<br/><small>{title}</small>'
                        ],
                        store: 'EmployeesStore'
                    }
                ]
            }
        ]
    }

});