/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.HomePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.homepanel',

    requires: [
        'Ext.Img',
        'Ext.Spacer',
        'Ext.field.Text',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'homePanel',
        layout: 'fit',
        items: [
            {
                xtype: 'container',
                itemId: 'homeContainer',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'image',
                        flex: 1,
                        height: '22%',
                        width: '100%',
                        src: 'http://test.decisionlink.com/images/Logo_Actual_Size_VSA.png'
                    },
                    {
                        xtype: 'container',
                        itemId: 'accountContainer',
                        items: [
                            {
                                xtype: 'spacer',
                                height: 10
                            },
                            {
                                xtype: 'textfield',
                                itemId: 'accountNameField',
                                label: 'Account',
                                labelWidth: '40%',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                itemId: 'userNameField',
                                label: 'Name',
                                labelWidth: '40%',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                itemId: 'emailField',
                                label: 'Email',
                                labelWidth: '40%',
                                readOnly: true
                            },
                            {
                                xtype: 'spacer',
                                height: 10
                            },
                            {
                                xtype: 'textfield',
                                label: 'Value Propositions',
                                labelWidth: '100%',
                                readOnly: true
                            },
                            {
                                xtype: 'spacer',
                                height: 10
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 2,
                        itemId: 'VPListContainer',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'list',
                                itemId: 'VPList',
                                itemTpl: [
                                    '<div class=“info” width=“40” height=“40”/>{name}<br/><small>Revenue: ${oppty_revenue}</small>'
                                ],
                                store: 'AccountScenariosStore'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'list',
                hidden: true,
                itemId: 'validateList',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ],
                store: 'ValidateStore'
            },
            {
                xtype: 'list',
                hidden: true,
                itemId: 'hiddenList',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ],
                store: 'SuccessStore'
            }
        ]
    }

});