/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.HomePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.homepanel',

    requires: [
        'Ext.Img',
        'Ext.field.Search',
        'Ext.field.Select',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'homePanel',
        layout: 'fit',
        items: [
            {
                xtype: 'container',
                itemId: 'homeContainer',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'image',
                        flex: 1,
                        centered: false,
                        height: 10,
                        src: 'http://test.decisionlink.com/images/Logo_Actual_Size_VSA.png'
                    },
                    {
                        xtype: 'searchfield',
                        itemId: 'searchField',
                        label: 'Search',
                        placeHolder: 'Enter Company'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'selectField',
                        margin: 5,
                        label: 'By:',
                        options: [
                            {
                                text: 'Company',
                                value: 1
                            },
                            {
                                text: 'DUNS',
                                value: 2
                            },
                            {
                                text: 'Ticker',
                                value: 3
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 2,
                        hidden: false,
                        itemId: 'searchListContainer',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'list',
                                itemId: 'searchList',
                                itemTpl: [
                                    '<div>{name}</div>'
                                ],
                                store: 'SearchStore'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'list',
                hidden: true,
                itemId: 'validateList',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ],
                store: 'ValidateStore'
            },
            {
                xtype: 'list',
                hidden: true,
                itemId: 'hiddenList',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ],
                store: 'SuccessStore'
            }
        ]
    }

});