/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.view.LoginPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.loginPanel',

    requires: [
        'Ext.field.Password',
        'Ext.Container',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        centered: true,
        id: 'loginPanel',
        hideOnMaskTap: true,
        modal: true,
        items: [
            {
                xtype: 'textfield',
                border: 3,
                id: 'usernameField',
                style: 'border-color: black; border-style: solid;',
                label: 'Username',
                labelWidth: '45%',
                labelWrap: true,
                autoCapitalize: false
            },
            {
                xtype: 'passwordfield',
                border: 3,
                id: 'passwordField',
                style: 'border-color: black; border-style: solid;',
                label: 'Password',
                labelWidth: '45%',
                labelWrap: true
            },
            {
                xtype: 'container',
                border: 3,
                id: 'buttonContainer',
                padding: 10,
                style: 'border-color: black; border-style: solid;',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'loginButton',
                        padding: 3,
                        width: '30%',
                        text: 'Login'
                    },
                    {
                        xtype: 'spacer',
                        width: 20
                    },
                    {
                        xtype: 'button',
                        id: 'cancelButton',
                        padding: 3,
                        width: '30%',
                        text: 'Cancel'
                    }
                ]
            }
        ]
    }

});