/*
 * File: app/view/MyDataItem.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.view.MyDataItem', {
    extend: 'Ext.dataview.component.DataItem',

    requires: [
        'Ext.Component'
    ],

    config: {
        padding: 10,
        layout: 'hbox',
        items: [
            {
                xtype: 'component',
                flex: 1,
                html: 'Sample component inside dataitem'
            }
        ]
    },

    updateRecord: function(record) {
        // Provide an implementation to update this container's child items
    }

});