/*
 * File: app/view/OpportunityCostDetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.view.OpportunityCostDetailPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.opportunitycostdetailpanel',

    requires: [
        'Ext.field.Select',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.field.Hidden',
        'Ext.ActionSheet'
    ],

    config: {
        scrollable: 'vertical',
        items: [
            {
                xtype: 'selectfield',
                itemId: 'costTypeSelectField',
                label: 'Type',
                labelWidth: '40%',
                labelWrap: true,
                options: [
                    {
                        text: 'Choose Type',
                        value: 0
                    },
                    {
                        text: 'License',
                        value: 1
                    },
                    {
                        text: 'Infrastructure',
                        value: 2
                    },
                    {
                        text: 'Maintenance',
                        value: 3
                    },
                    {
                        text: 'Labor',
                        value: 4
                    },
                    {
                        text: 'Customer Labor',
                        value: 5
                    },
                    {
                        text: 'Subscription',
                        value: 6
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'textfield',
                itemId: 'costValueField',
                label: 'Cost',
                labelWidth: '40%',
                labelWrap: true
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'selectfield',
                itemId: 'accrualTypeSelectField',
                label: 'Accrual Type',
                labelWidth: '40%',
                labelWrap: true,
                options: [
                    {
                        text: 'Choose Type',
                        value: 0
                    },
                    {
                        text: 'One Time',
                        value: 1
                    },
                    {
                        text: 'Annual',
                        value: 2
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'button',
                itemId: 'saveCostButton',
                margin: 10,
                text: 'Save Cost'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'costIdField',
                readOnly: false
            },
            {
                xtype: 'actionsheet',
                hidden: true,
                itemId: 'deleteCostActionSheet',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'deleteCostButton',
                        ui: 'decline',
                        text: 'Delete Cost'
                    },
                    {
                        xtype: 'button',
                        itemId: 'cancelDeleteButton',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'hiddenfield',
                        itemId: 'costIdField'
                    }
                ]
            }
        ]
    }

});