/*
 * File: app/view/SearchPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SearchPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.searchpanel',

    requires: [
        'Ext.tab.Bar',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.field.Search',
        'Ext.form.FieldSet',
        'Ext.field.Select'
    ],

    config: {
        navView: 'searchpanel',
        tabBar: {
            docked: 'top',
            layout: {
                type: 'hbox',
                pack: 'center'
            }
        },
        items: [
            {
                xtype: 'container',
                title: 'Saved',
                itemId: 'savedPanel',
                layout: 'fit',
                items: [
                    {
                        xtype: 'list',
                        itemId: 'savedList',
                        itemTpl: [
                            '<div class=“info” width=“40” height=“40”/>Name: {name}<br/><small>Revenue: ${revenue} M</small>'
                        ],
                        store: 'SavedStore'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Search',
                itemId: 'searchPanel',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'searchfield',
                        itemId: 'searchField',
                        label: 'Search',
                        placeHolder: 'Enter Company'
                    },
                    {
                        xtype: 'fieldset',
                        itemId: 'myFieldSet',
                        layout: 'vbox',
                        title: '',
                        items: [
                            {
                                xtype: 'selectfield',
                                itemId: 'selectField',
                                label: 'By:',
                                options: [
                                    {
                                        text: 'Company',
                                        value: 1
                                    },
                                    {
                                        text: 'DUNS',
                                        value: 2
                                    },
                                    {
                                        text: 'Ticker',
                                        value: 3
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 1,
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'list',
                                itemId: 'searchList',
                                itemTpl: [
                                    '<div>{name}</div>'
                                ],
                                store: 'SearchStore'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});