/*
 * File: app/view/ValueFormulaDetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.view.ValueFormulaDetailPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.valueformuladetailpanel',

    requires: [
        'Ext.Spacer',
        'Ext.field.Spinner',
        'Ext.field.Select',
        'Ext.Container',
        'Ext.field.Slider',
        'Ext.Label',
        'Ext.field.Checkbox',
        'Ext.Button',
        'Ext.field.Hidden'
    ],

    config: {
        alt_metric_id: '0',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'textfield',
                itemId: 'metricField',
                label: 'Metric',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'textfield',
                itemId: 'driverFactorField',
                label: 'Driver Factor',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'textfield',
                itemId: 'driverFactorValueField',
                margin: 10,
                label: 'Value',
                labelWidth: '40%',
                labelWrap: true
            },
            {
                xtype: 'spinnerfield',
                itemId: 'improveFactorSpinner',
                label: 'Improve Factor',
                labelWidth: '40%',
                labelWrap: true,
                ui: 'string'
            },
            {
                xtype: 'textfield',
                itemId: 'improveFactorUnitField',
                margin: 10,
                label: 'Unit',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'selectfield',
                itemId: 'sourceSelectField',
                label: 'Source',
                labelWidth: '40%',
                labelWrap: true,
                options: [
                    {
                        text: 'Choose Source',
                        value: 0
                    },
                    {
                        text: 'Customer',
                        value: 1
                    },
                    {
                        text: 'Estimate',
                        value: 2
                    },
                    {
                        text: 'Research',
                        value: 3
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'textfield',
                itemId: 'financialFactorField',
                label: 'Financial Factor',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'spinnerfield',
                itemId: 'financialFactorValueSpinner',
                margin: 10,
                label: 'Value',
                labelWidth: '40%',
                labelWrap: true,
                ui: 'string',
                stepValue: 1
            },
            {
                xtype: 'container',
                itemId: 'year1container',
                margin: 2,
                layout: 'hbox',
                items: [
                    {
                        xtype: 'sliderfield',
                        flex: 6,
                        itemId: 'year1growth',
                        label: 'Year 1 Growth',
                        labelWidth: '40%',
                        labelWrap: true,
                        increment: 10
                    },
                    {
                        xtype: 'label',
                        flex: 1,
                        itemId: 'year1label',
                        margin: 3
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'year2container',
                margin: 2,
                layout: 'hbox',
                items: [
                    {
                        xtype: 'sliderfield',
                        flex: 6,
                        itemId: 'year2growth',
                        label: 'Year 2 Growth',
                        labelWidth: '40%',
                        labelWrap: true,
                        increment: 10
                    },
                    {
                        xtype: 'label',
                        flex: 1,
                        itemId: 'year2label',
                        margin: 3
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'year3container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'sliderfield',
                        flex: 6,
                        itemId: 'year3growth',
                        margin: 2,
                        label: 'Year 3 Growth',
                        labelWidth: '40%',
                        labelWrap: true,
                        increment: 10
                    },
                    {
                        xtype: 'label',
                        flex: 1,
                        itemId: 'year3label',
                        margin: 3
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'year4container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'sliderfield',
                        flex: 6,
                        itemId: 'year4growth',
                        margin: 2,
                        label: 'Year 4 Growth',
                        labelWidth: '40%',
                        labelWrap: true,
                        increment: 10
                    },
                    {
                        xtype: 'label',
                        flex: 1,
                        itemId: 'year4label',
                        margin: 3
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'year5container',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'sliderfield',
                        flex: 6,
                        itemId: 'year5growth',
                        margin: 2,
                        label: 'Year 5 Growth',
                        labelWidth: '40%',
                        labelWrap: true,
                        increment: 10
                    },
                    {
                        xtype: 'label',
                        flex: 1,
                        itemId: 'year5label',
                        margin: 3
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'checkboxfield',
                itemId: 'applyAll',
                label: 'Apply to all metrics',
                labelWidth: '70%',
                labelWrap: true
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'textfield',
                itemId: 'valueFormulaTotalField',
                label: 'Total',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'button',
                itemId: 'saveValueFormulaButton',
                margin: 10,
                text: 'Save Value Formula'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'metricIdField'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'unitTypeIdField'
            }
        ],
        listeners: [
            {
                fn: 'onYear1growthChange',
                event: 'change',
                delegate: '#year1growth'
            },
            {
                fn: 'onYear2growthChange',
                event: 'change',
                delegate: '#year2growth'
            },
            {
                fn: 'onYear3growthChange',
                event: 'change',
                delegate: '#year3growth'
            },
            {
                fn: 'onYear4growthChange',
                event: 'change',
                delegate: '#year4growth'
            },
            {
                fn: 'onYear5growthChange',
                event: 'change',
                delegate: '#year5growth'
            }
        ]
    },

    onYear1growthChange: function(me, sl, thumb, newValue, oldValue, eOpts) {
        Ext.ComponentQuery.query('valueformuladetailpanel #year1container #year1label')[0].setHtml('<p>' + newValue + '</p>');
    },

    onYear2growthChange: function(me, sl, thumb, newValue, oldValue, eOpts) {
        Ext.ComponentQuery.query('valueformuladetailpanel #year2container #year2label')[0].setHtml('<p>' + newValue + '</p>');
    },

    onYear3growthChange: function(me, sl, thumb, newValue, oldValue, eOpts) {
        Ext.ComponentQuery.query('valueformuladetailpanel #year3container #year3label')[0].setHtml('<p>' + newValue + '</p>');
    },

    onYear4growthChange: function(me, sl, thumb, newValue, oldValue, eOpts) {
        Ext.ComponentQuery.query('valueformuladetailpanel #year4container #year4label')[0].setHtml('<p>' + newValue + '</p>');
    },

    onYear5growthChange: function(me, sl, thumb, newValue, oldValue, eOpts) {
        Ext.ComponentQuery.query('valueformuladetailpanel #year5container #year5label')[0].setHtml('<p>' + newValue + '</p>');
    }

});