/*
 * File: app/model/ValueFormulas.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.model.ValueFormulas', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'metric'
            },
            {
                name: 'sqq'
            },
            {
                name: 'sqq_value'
            },
            {
                name: 'impact'
            },
            {
                name: 'abbr'
            },
            {
                name: 'source_type_id'
            },
            {
                name: 'sqq2'
            },
            {
                name: 'sqq2_value'
            },
            {
                name: 'y1_raw'
            },
            {
                name: 'alt_metric_id'
            },
            {
                name: 'metric_id'
            },
            {
                name: 'unit_type_id'
            },
            {
                name: 'sqq_y1'
            },
            {
                name: 'sqq_y2'
            },
            {
                name: 'sqq_y3'
            },
            {
                name: 'sqq_y4'
            },
            {
                name: 'sqq_y5'
            }
        ]
    }
});