/*
 * File: app/model/AccountScenarios.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.model.AccountScenarios', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'name'
            },
            {
                name: 'company_id'
            },
            {
                name: 'company'
            },
            {
                name: 'user_id'
            },
            {
                name: 'oppty_revenue'
            },
            {
                name: 'wacc'
            },
            {
                name: 'term'
            },
            {
                name: 'area_type_id'
            },
            {
                name: 'situation_type_id'
            },
            {
                name: 'baseline_type_id'
            },
            {
                name: 'yr1_benefit_sum'
            },
            {
                name: 'yr2_benefit_sum'
            },
            {
                name: 'yr3_benefit_sum'
            },
            {
                name: 'yr4_benefit_sum'
            },
            {
                name: 'yr5_benefit_sum'
            },
            {
                name: 'yr1_cost_sum'
            },
            {
                name: 'yrx_cost_sum'
            },
            {
                name: 'user_name'
            }
        ]
    }
});