/*
 * File: app/view/NavMenu.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.view.NavMenu', {
    extend: 'Ext.Panel',
    alias: 'widget.navmenu',

    requires: [
        'Ext.Button'
    ],

    config: {
        fullscreen: false,
        hidden: true,
        itemId: 'navMenu',
        left: 0,
        padding: 10,
        hideOnMaskTap: true,
        layout: 'vbox',
        modal: true,
        items: [
            {
                xtype: 'button',
                navView: 'homepanel',
                margin: 5,
                iconCls: 'home',
                text: 'Search'
            },
            {
                xtype: 'button',
                navView: 'searchpanel',
                margin: 5,
                iconCls: 'favorites',
                text: 'Saved Accounts'
            },
            {
                xtype: 'button',
                navView: 'accountscenariospanel',
                margin: 5,
                iconCls: 'organize',
                text: 'Value Propositions'
            },
            {
                xtype: 'button',
                navView: 'accountpanel',
                margin: 5,
                iconCls: 'user',
                text: 'My Account'
            }
        ]
    }

});