/*
 * File: app/view/NewVPPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.view.NewVPPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.newvppanel',

    requires: [
        'Ext.field.Checkbox',
        'Ext.Spacer',
        'Ext.field.Text',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Button'
    ],

    config: {
        scrollable: 'vertical',
        items: [
            {
                xtype: 'checkboxfield',
                itemId: 'accountRevenueCheckbox',
                label: 'Change the Account Revenue',
                labelWidth: '75%',
                labelWrap: true
            },
            {
                xtype: 'spacer',
                height: 15
            },
            {
                xtype: 'container',
                hidden: true,
                itemId: 'detailContainer',
                margin: 10,
                layout: 'fit',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'companyNameField',
                        label: 'Company Name',
                        labelWidth: '40%',
                        labelWrap: true,
                        readOnly: true
                    },
                    {
                        xtype: 'spacer',
                        height: 10
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'totalRevenueField',
                        label: 'Total Company Revenue',
                        labelWidth: '40%',
                        labelWrap: true,
                        readOnly: true
                    },
                    {
                        xtype: 'spacer',
                        height: 10
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'companyRevenueField',
                        label: 'Company Revenue (M)',
                        labelWidth: '40%',
                        labelWrap: true
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 15
            },
            {
                xtype: 'container',
                itemId: 'newInfoContainer',
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        itemId: 'nameContainer',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'nameField',
                                label: 'Name',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'spacer',
                                height: 10
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        itemId: 'solutionsListContainer',
                        margin: 10,
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'dataview',
                                height: 160,
                                itemId: 'solutionsList',
                                defaultType: 'checkboxitem',
                                store: 'SolutionsStore',
                                useComponents: true
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        itemId: 'saveVPButtonContainer',
                        items: [
                            {
                                xtype: 'spacer',
                                height: 15
                            },
                            {
                                xtype: 'button',
                                itemId: 'saveVPButton',
                                margin: 10,
                                text: 'Save Value Proposition'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});