/*
 * File: app/view/SecondarySQQDetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.view.SecondarySQQDetailPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.secondarysqqdetailpanel',

    requires: [
        'Ext.Spacer',
        'Ext.field.Select',
        'Ext.Button',
        'Ext.field.Hidden'
    ],

    config: {
        items: [
            {
                xtype: 'textfield',
                itemId: 'salesQuestionField',
                label: 'Sales Question',
                labelAlign: 'top',
                readOnly: true
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'textfield',
                itemId: 'sqqAnswerField',
                label: 'Answer',
                labelWidth: '40%'
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'selectfield',
                itemId: 'sourceSelectField',
                label: 'Source',
                labelWidth: '40%',
                options: [
                    {
                        text: 'Choose Source',
                        value: 0
                    },
                    {
                        text: 'Customer',
                        value: 1
                    },
                    {
                        text: 'Estimate',
                        value: 2
                    },
                    {
                        text: 'Research',
                        value: 3
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'button',
                itemId: 'saveSecondarySQQButton',
                margin: 10,
                text: 'Save Sales Question'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'sqq2IdField'
            }
        ]
    }

});