/*
 * File: app/view/ValueFormulaDetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DecisionLink.view.ValueFormulaDetailPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.valueformuladetailpanel',

    requires: [
        'Ext.Spacer',
        'Ext.field.Spinner',
        'Ext.field.Select',
        'Ext.Button',
        'Ext.field.Hidden'
    ],

    config: {
        alt_metric_id: '0',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'textfield',
                itemId: 'metricField',
                label: 'Metric',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'textfield',
                itemId: 'driverFactorField',
                label: 'Driver Factor',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'textfield',
                itemId: 'driverFactorValueField',
                margin: 10,
                label: 'Value',
                labelWidth: '40%',
                labelWrap: true
            },
            {
                xtype: 'spinnerfield',
                itemId: 'improveFactorSpinner',
                label: 'Improve Factor',
                labelWidth: '40%',
                labelWrap: true
            },
            {
                xtype: 'textfield',
                itemId: 'improveFactorUnitField',
                margin: 10,
                label: 'Unit',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'selectfield',
                itemId: 'sourceSelectField',
                label: 'Source',
                labelWidth: '40%',
                options: [
                    {
                        text: 'Choose Source',
                        value: 0
                    },
                    {
                        text: 'Customer',
                        value: 1
                    },
                    {
                        text: 'Estimate',
                        value: 2
                    },
                    {
                        text: 'Research',
                        value: 3
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'textfield',
                itemId: 'financialFactorField',
                label: 'Financial Factor',
                labelWidth: '40%',
                labelWrap: true,
                readOnly: true
            },
            {
                xtype: 'spinnerfield',
                itemId: 'financialFactorValueSpinner',
                margin: 10,
                label: 'Value',
                labelWidth: '40%',
                labelWrap: true,
                stepValue: 1
            },
            {
                xtype: 'spacer',
                height: 10
            },
            {
                xtype: 'textfield',
                itemId: 'valueFormulaTotalField',
                label: 'Total',
                labelWidth: '40%',
                readOnly: true
            },
            {
                xtype: 'button',
                itemId: 'saveValueFormulaButton',
                margin: 10,
                text: 'Save Value Formula'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'metricIdField'
            },
            {
                xtype: 'hiddenfield',
                itemId: 'unitTypeIdField'
            }
        ]
    }

});